apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fastapi
  labels: { app: sample-fastapi }
spec:
  replicas: 1
  selector:
    matchLabels: { app: sample-fastapi }
  template:
    metadata:
      labels: { app: sample-fastapi }
    spec:
      containers:
        - name: app
          image: acrmsoumiteastus01.azurecr.io/sample-fastapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet: { path: /docs, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /docs, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: sample-fastapi
spec:
  type: LoadBalancer
  selector: { app: sample-fastapi }
  ports:
    - name: http
      port: 80
      targetPort: 8000
